<%@page import="com.openmarket.xcelerate.interfaces.ITemplateAssetManager"%>
<%@page import="com.openmarket.assetframework.interfaces.AssetTypeManagerFactory"%>
<%@page import="com.openmarket.assetframework.interfaces.IAssetTypeManager"%>
<%@page import="com.fatwire.assetapi.data.AssetDataManagerImpl"%>
<%@page import="com.fatwire.assetapi.data.AssetDataManager"%>
<%@page import="com.fatwire.services.beans.asset.basic.template.ArgumentBean"%>
<%@page import="com.fatwire.services.TemplateService"%>
<%@page import="com.fatwire.system.SessionFactory"%>
<%@page import="com.fatwire.services.ServicesManager"%>
<%@page import="com.fatwire.system.Session"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.Collections"%>
<%@page import="com.fatwire.mobility.util.MobilityUtils"%>
<%@page import="com.fatwire.mobility.beans.DeviceGroupBean"%>
<%@page import="com.openmarket.xcelerate.asset.WebRootsManager"%>
<%@page import="java.util.HashMap"%>
<%@page import="java.util.Map"%>
<%@page import="com.openmarket.xcelerate.asset.WebReferencesManager"%>
<%@page import="java.util.LinkedList"%>
<%@page import="java.util.List"%>
<%@page import="org.apache.commons.lang.StringUtils"%>
<%@ taglib prefix="cs" uri="futuretense_cs/ftcs1_0.tld" %>
<%@ taglib prefix="ics" uri="futuretense_cs/ics.tld" %>
<%@ taglib prefix="xlat" uri="futuretense_cs/xlat.tld"%>
<%//
// OpenMarket/Gator/AttributeTypes/DisplayWebReferences
//
// INPUT
//
// OUTPUT
//%>
<cs:ftcs>
<%
	String webreferencePrefix = "ContentDetails:Webreferences:";
	String webreference = ":Webreference:";
	int total = Integer.parseInt(StringUtils.defaultIfEmpty(ics.GetVar("ContentDetails:Webreferences:Total"), "0"));
	IAssetTypeManager atm = AssetTypeManagerFactory.getATM(ics);
	ITemplateAssetManager tam = (ITemplateAssetManager)atm.locateAssetManager("Template");
	Session ses = SessionFactory.getSession();
	ServicesManager servicesManager = (ServicesManager)ses.getManager( ServicesManager.class.getName() );
	TemplateService templateDataService = servicesManager.getTemplateService();	
	WebRootsManager webrootsManager = new WebRootsManager(ics);
	Map<String,String> urlMapforDisplay = new HashMap<String, String>();
	List<Integer> assetURLindexes = new ArrayList<Integer>();
	List<Integer> blobURLindexes = new ArrayList<Integer>();
	for (int i = 0; i < total; i++) {
		String webreferencePrefixComputed = webreferencePrefix + i +webreference;
		String field = ics.GetVar(webreferencePrefixComputed+"field");
		String webroot = ics.GetVar(webreferencePrefixComputed+"webroot");
		String webRootURL = webrootsManager.getWebRoot(webroot,null);
		String url = ics.GetVar(webreferencePrefixComputed+"webreferenceurl");	
		String deviceGroup = ics.GetVar(webreferencePrefixComputed+"dgroup");
		String wrapper = ics.GetVar(webreferencePrefixComputed+"wrapper");
		if(!StringUtils.isEmpty(webRootURL)) {
			url =  webRootURL.endsWith("/") ? webRootURL + url: webRootURL +"/"+ url;
		}
		urlMapforDisplay.put(webroot+ics.GetVar(webreferencePrefixComputed+"webreferenceurl"),url);
		if(StringUtils.isEmpty(field)) {
			assetURLindexes.add(i);
		} else {
			blobURLindexes.add(i);
		}
	}
	List<DeviceGroupBean> deviceGroupList = MobilityUtils.getDeviceGroups(ics);
	Map<String,List<String>> deviceGroupMap = new HashMap<String,List<String>>();
	Collections.reverse(deviceGroupList);
	for(DeviceGroupBean deviceGroup:deviceGroupList) {
		String deviceSuffix = deviceGroup.getDeviceGroupSuffix();
		if(deviceGroupMap.get(deviceSuffix) == null)
		{
			deviceGroupMap.put(deviceSuffix, new LinkedList<String>());
		}
		deviceGroupMap.get(deviceSuffix).add(deviceGroup.getName());
	}	
%>
<script>
function updateTableDetailView(index, elem, show , tablename) {
	if(tablename === "webref") {
		var detail = dojo.byId('webRefTableDetail_'+index);
	} else {
		var detail = dojo.byId('blobRefTableDetail_'+index);
	}
	if(show) {
		detail.style.display = "block";
		elem.innerHTML = "<xlat:stream key='UI/Forms/ViewLess'/>";
		elem.onclick = function() {
			updateTableDetailView(index, this, false,tablename);
		}
	} else {
		detail.style.display = "none";
		elem.innerHTML = "<xlat:stream key='UI/Forms/ViewMore'/>";
		elem.onclick = function() {
			updateTableDetailView(index, this, true,tablename);
		}
	}
	return false;
}
</script>
<div class="webRefWrapper webRefForm">
<%if(assetURLindexes.size() == 0) {%>
	<div class='webRefTableNoData'><xlat:stream key='UI/Forms/NoURL'/></div>
<% } else { %>
	
<table class="webRefTable">
	<tr>
		<th width="140" class="center"><xlat:stream key='UI/Forms/AutoGenerated'/></th>
		<th width="80" class="center"><xlat:stream key='UI/Forms/Status'/></th>
		<th><xlat:stream key='UI/Forms/Info'/></th>
	</tr>
<%
	webreferencePrefix = "ContentDetails:Webreferences:";
	webreference = ":Webreference:";	
	for (int i = 0; i < assetURLindexes.size(); i++) {
		int index = assetURLindexes.get(i);
		String webreferencePrefixComputed = webreferencePrefix + index +webreference;
		String webroot = ics.GetVar(webreferencePrefixComputed+"webroot");
		String wrapper = ics.GetVar(webreferencePrefixComputed+"wrapper");
		String redirectURL = ics.GetVar(webreferencePrefixComputed+"redirecturl");
		String redirectWebRoot = ics.GetVar(webreferencePrefixComputed+"redirectwebroot");		
		String webreferenceURL = ics.GetVar(webreferencePrefixComputed+"webreferenceurl");
		// Decode the URL for the display	
		String displayWebreferenceURL =  WebReferencesManager.decodeURL(urlMapforDisplay.get(webroot+webreferenceURL));
		long patternid = Long.parseLong(ics.GetVar(webreferencePrefixComputed+"patternid"));
		String displayRedirectURL = redirectURL;
		String params = ics.GetVar(webreferencePrefixComputed+"params");
		String template = ics.GetVar(webreferencePrefixComputed+"template");
		String deviceGroup = ics.GetVar(webreferencePrefixComputed+"dgroup");		
		List<String> deviceGroupNameList = deviceGroupMap.get(deviceGroup);
		String httpStatus = ics.GetVar(webreferencePrefixComputed+"httpstatus");
		boolean isRedirect = !"200".equals(httpStatus) ;		
		if(StringUtils.isNotEmpty(redirectWebRoot))
		{
			displayRedirectURL = urlMapforDisplay.get(redirectWebRoot+redirectURL);
		}	
%>	
	<tr class="tableRow<%=i%2%>">
		<td class="center"><%if(patternid >0)  {%><xlat:stream key='dvin/Common/Yes'/> <% }else { %><xlat:stream key='dvin/Common/No'/> <%} %></td>
		<td class="center"><img src="js/fw/images/ui/wem/<%=httpStatus%>.png" alt="" title="" /></td>
		<td><strong><xlat:stream key='dvin/UI/CSAdminForms/URL'/>:</strong> <%=displayWebreferenceURL%>
		<%if(isRedirect) { %>
			<br><strong><xlat:stream key='UI/Forms/RedirectTo'/>:</strong> <%=displayRedirectURL %>
		<% } %>
		<div id="webRefTableDetail_<%=index%>" class="webRefTableDetail">
		<strong><xlat:stream key='dvin/UI/Template'/>:</strong> <%=template%>		
		<%if(StringUtils.isNotEmpty(wrapper))  {%>
			<br/><strong><xlat:stream key='dvin/UI/Wrapper'/>:</strong> <%=wrapper%>
		<% } %>
		<%if(deviceGroupNameList!=null && deviceGroupNameList.size() > 0) { %> 
			<br/><strong><xlat:stream key='dvin/UI/Admin/DeviceGroup'/>:</strong> <%=StringUtils.join(deviceGroupNameList, ",")%>
		<%} %>
		<%if(StringUtils.isNotEmpty(params))  {%>
					<br /><strong><xlat:stream key='dvin/AT/Template/Parameters'/>:<br></strong>
			<%
					String assetType = tam.getAssetTypeFromPageName(template);
					String tname = tam.getTemplateNameFromPageName(template);								
					List<ArgumentBean> templateArgs = templateDataService.getTemplateArguments( tname, assetType );
					String[] paramArr = params.split("&");
					for (String str : paramArr) {
						String paramValue = "&nbsp;&nbsp;&nbsp;&nbsp;";
						String[] strArr = str.split("=");
						for(ArgumentBean arguments:templateArgs) {
							if(strArr.length == 2) {
								if(strArr[0].equals(arguments.getName())) {
									paramValue += arguments.getDescription() + "=";								
										if(arguments.getValues().size() > 0)
										{
											 for(Map.Entry<String,String> entry:arguments.getValues().entrySet()) {
												 String value =  entry.getKey();
												 if(value.equals(strArr[1])) {
													out.println(paramValue + entry.getValue() +"<br>");																						 
												 }
											 }
										} else {
												 out.println(paramValue + strArr[1]+"<br>");														 
										}
									}
								}
							}
						}
			 		}
				%>
		
		</div>
		<div class='viewLink'><a href='#' onclick='updateTableDetailView(<%=index%>, this, true,"webref")'><xlat:stream key='UI/Forms/ViewMore'/></a></div>
		</td>
	</tr>
	<% } %>
</table>
<% } %>
<%if(blobURLindexes.size() > 0) { %>
<h3><xlat:stream key='UI/Forms/BlobURL'/></h3>
<table class="webRefTable">
	<tr>
		<th width="140" class="center"><xlat:stream key='UI/Forms/AutoGenerated'/></th>
		<th width="80" class="center"><xlat:stream key='UI/Forms/Status'/></th>
		<th><xlat:stream key='UI/Forms/Info'/></th>
	</tr>
<%
	webreferencePrefix = "ContentDetails:Webreferences:";
	webreference = ":Webreference:";	
	for (int i = 0; i < blobURLindexes.size(); i++) {
		int index = blobURLindexes.get(i);
		String webreferencePrefixComputed = webreferencePrefix + index +webreference;
		String webroot = ics.GetVar(webreferencePrefixComputed+"webroot");
		String wrapper = ics.GetVar(webreferencePrefixComputed+"wrapper");
		String redirectURL = ics.GetVar(webreferencePrefixComputed+"redirecturl");
		String redirectWebRoot = ics.GetVar(webreferencePrefixComputed+"redirectwebroot");		
		String webreferenceURL = ics.GetVar(webreferencePrefixComputed+"webreferenceurl");
		// Decode the URL for the display
		String displayWebreferenceURL =  WebReferencesManager.decodeURL(urlMapforDisplay.get(webroot+webreferenceURL));
		long patternid = Long.parseLong(ics.GetVar(webreferencePrefixComputed+"patternid"));
		String displayRedirectURL = redirectURL;
		String params = ics.GetVar(webreferencePrefixComputed+"params");
		// Remove the filename from the display since we add it.
		String[] parameterString = StringUtils.split(params, ",");
		Map<String, String> parameterMap = new HashMap<String, String>();
		StringBuilder filteredParams = new StringBuilder();
		//for (String parameters : parameterString)
		for (int j = 0; j < parameterString.length; j++)
		{
			String[] parameter = StringUtils.split(parameterString[j], "=");
			if (parameter.length == 2 && !"filename".equals( parameter[0]))
			{
				if(StringUtils.isNotBlank(filteredParams.toString())) {
					filteredParams.append(",");
				}
				filteredParams.append(parameter[0]).append("=").append(parameter[1]);
			}			
		}		
		String httpStatus = ics.GetVar(webreferencePrefixComputed+"httpstatus");
		boolean isRedirect = !"200".equals(httpStatus) ;		
		if(StringUtils.isNotEmpty(redirectWebRoot))
		{
			displayRedirectURL = urlMapforDisplay.get(redirectWebRoot+redirectURL);
		}	
%>	
	<tr class="tableRow<%=i%2%>">
		<td class="center"><%if(patternid >0)  {%><xlat:stream key='dvin/Common/Yes'/> <% }else { %><xlat:stream key='dvin/Common/No'/> <%} %></td>
		<td class="center"><img src="js/fw/images/ui/wem/<%=httpStatus%>.png" alt="" title="" /></td>
		<td><strong><xlat:stream key='dvin/UI/CSAdminForms/URL'/>:</strong> <%=displayWebreferenceURL%>
		<%if(isRedirect) { %>
			<br><strong><xlat:stream key='UI/Forms/RedirectTo'/>:</strong> <%=displayRedirectURL %>
		<% } %>
		<div id="blobRefTableDetail_<%=index%>" class="webRefTableDetail">
		<strong><xlat:stream key='dvin/AdminForms/FieldName'/>:</strong> <%=ics.GetVar(webreferencePrefixComputed+"field")%>
		<%if(StringUtils.isNotEmpty(filteredParams.toString()))  {%>
					<br /><strong><xlat:stream key='dvin/AT/Template/Parameters'/>:</strong> <%=filteredParams%>
		<% } %>
				
		</div>
		<div class='viewLink'><a href='#' onclick='updateTableDetailView(<%=index%>, this, true, "blobref")'><xlat:stream key='UI/Forms/ViewMore'/></a></div>
		</td>
	</tr>
	<% } %>
</table>
<%} %>
</div>
</cs:ftcs>