<%@ taglib prefix="cs" uri="futuretense_cs/ftcs1_0.tld" %>
<%@ taglib prefix="ics" uri="futuretense_cs/ics.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="xlat" uri="futuretense_cs/xlat.tld" %>
<%@ taglib prefix="string" uri="futuretense_cs/string.tld" %>
<%@ taglib prefix="dateformat" uri="futuretense_cs/dateformat.tld" %>
<%@ taglib prefix="asset" uri="futuretense_cs/asset.tld"%>
<%@ taglib prefix="assettype" uri="futuretense_cs/assettype.tld" %>
<%@ taglib prefix="satellite" uri="futuretense_cs/satellite.tld" %>

<cs:ftcs>
<!-- OpenMarket/Xcelerate/AssetType/Segments/ContentForm
--
-	Form for creating/editing  Segments
-- INPUT
--			ContentDetails: result of a scatter
-- OUTPUT
--
-- HISTORY 
   [2007-09-17 KG]
   * added XSS scripting fixes (adapted from 6.3 fixes); search for isCleanString
   * changed definitions of 'obj' to just forms[0] (not .elements[0])
   * performed a bit of code cleanup, though there's plenty left that could be done...
   [2007-10-09 KG]
   * XSS revision: minimized set of restricted characters.
-->

<ics:if condition='<%="standard".equals(ics.GetVar("cs_environment"))%>'>
<ics:then>
	<satellite:link assembler="query" pagename="OpenMarket/Xcelerate/Actions/EditFront" outstring="editBaseURL">
		<satellite:argument name="cs_environment" value='addref'/>
		<satellite:argument name="cs_formmode" value='<%=ics.GetVar("cs_formmode")%>'/>
	</satellite:link>
</ics:then>
<ics:else>
	<satellite:link assembler="query" pagename="OpenMarket/Xcelerate/Actions/EditFront" outstring="editBaseURL">
		<satellite:argument name="cs_environment" value='<%=ics.GetVar("cs_environment")%>'/>
		<satellite:argument name="cs_formmode" value='<%=ics.GetVar("cs_formmode")%>'/>
	</satellite:link>
</ics:else>
</ics:if>

<ics:callelement element="OpenMarket/Xcelerate/Scripts/FormatDate" />
<ics:callelement element="OpenMarket/Xcelerate/Scripts/ValidateInputForXSS" />

<asset:getassettype name='<%=ics.GetVar("assetname")%>' outname="at"/>
<assettype:get name="at" field="description" output="at:description"/>


<script type="text/javascript">
var obj = document.forms[0];

function submitForm()
{
	removeDummyCell();
	captureRuleSet();
	return checkfields();
}

function SetCancelFlag () {
	if(confirm("<xlat:stream key="dvin/Common/CancelClicked" escape="true" encode="false"/>"))
	{
		obj.elements['upcommand'].value="cancel";
		obj.submit();
		return false;
	}
}

function getAssetName()
{
	return obj.elements['Segments:name'].value;
}

function checkfields()
{
	var nameVal = obj.elements['Segments:name'].value;
    if (dojo.trim(nameVal).length == 0)
	{                                                      
		alert('<xlat:stream key="dvin/Assetmaker/SpecifyUniqueName" escape="true" encode="false"/>');
		obj.elements['Segments:name'].focus();
		return false;
	}
	var isclean = isCleanString(obj.elements['Segments:name'].value, '<">\'', true);
	if (!isclean) {
		alert('<xlat:stream key="dvin/AT/Common/Apostrophenotallowedinname" escape="true" encode="false"/>');
		obj.elements['Segments:name'].focus();
		return false;
	}
	
	if(!checkStartEndDateValidity()) 
		return false;

	if (!validateRuleSet())
		return false;
	
	obj.submit();	// Do the Save
	
	return false;	// I don't understand why we return a value from this function.
					// I especially don't see why we return false here... 
					// but everyone does it...
}
</script>

<ics:setvar name="OptionName" value=""/>
<ics:setvar name="SValueName" value=""/>
<ics:setvar name="STypeName" value=""/>
<ics:setvar name="HValueName" value=""/>
<ics:setvar name="WrongPage" value=""/>

<ics:callelement element="OpenMarket/Xcelerate/AssetType/Segments/SaveRulesetTuples">
	<ics:argument name="Prefix" value="Segments"/>
</ics:callelement>

<!-- Fix for PR#19224.Added two variables for this mainly PickAttributeSelected and CriteriaOperationReq.PickAttributeSelected is set to true when the user clicks on history attribute from the history page.This would allow us to check if we want to delete the rule generated by the click on the attribute link.CriteriaOperationReq 
			was created to have an additonal variable to track the original action.The variable CriteriaOperatin changes during several actions on the add screen and cannot be used to remember the original criteria operation-->

<ics:if condition='<%=ics.GetVar("PickAttributeSelected") == null%>'>
<ics:then>
	<ics:setvar name="PickAttributeSelected" value=""/>
</ics:then>
</ics:if>

<ics:if condition='<%=ics.GetVar("CriteriaOperation") == null%>'>
<ics:then>
	<ics:setvar name="CriteriaOperation" value=""/>
</ics:then>
</ics:if>

<ics:if condition='<%=ics.GetVar("CriteriaOperationReq") == null%>'>
<ics:then>
	<ics:setvar name="CriteriaOperation" value=""/>
</ics:then>
</ics:if>

<ics:if condition='<%=ics.GetVar("RebuildScreen") == null%>'>
<ics:then>
	<ics:setvar name="RebuildScreen" value=""/>
</ics:then>
</ics:if>

<ics:if condition='<%=ics.GetVar("CriteriaRow") == null%>'>
<ics:then>
	<ics:setvar name="CriteriaRow" value=""/>
</ics:then>
</ics:if>

<ics:if condition='<%=ics.GetVar("CriteriaColumn") == null%>'>
<ics:then>
	<ics:setvar name="CriteriaColumn" value=""/>
</ics:then>
</ics:if>

<script type="text/javascript">
	var isEditMode=true;
	var isContributorMode = <%= "ucform".equals(ics.GetVar("cs_environment")) %>;
</script>

<ics:if condition='<%=ics.GetVar("SegRuleSetHint") == null%>'>
<ics:then>
	<ics:setvar name="SegRuleSetHint" value=""/>
</ics:then>
</ics:if>

<ics:callelement element="OpenMarket/Xcelerate/AssetType/Segments/CoFSetVar"/>

<!-- Load data for this specific Segment and some general supporting material -->
<ics:callelement element="OpenMarket/Xcelerate/AssetType/Segments/ContentFormLoadData"/>

<!-- Load Javascript to Render (and support Edit and Save of) the Segment data -->
<ics:callelement element="OpenMarket/Xcelerate/AssetType/Segments/ContentFormJavascript"/>

<!-- Dispatch to the appropriate place for the actual form elements -->
<ics:callelement element='OpenMarket/Xcelerate/AssetType/Segments/ContentForm1'/>

<input type="hidden" name="upcommand" value="submit"/>
<input type="hidden" name="SegmentsNextStep" value=""/>
<input type="hidden" name="SegmentsRuleScreen" value=""/>
<input type="hidden" name="SegmentsArg2" value=""/>
<input type="hidden" name="SegmentsArg3" value=""/>
<input type="hidden" name="OptionName" value=""/>

<string:encode variable="PickAttributeSelected" varname="PickAttributeSelected"/>
<input type="hidden" name="PickAttributeSelected" value='<%=ics.GetVar("PickAttributeSelected")%>' />

<string:encode variable="CriteriaOperationReq" varname="CriteriaOperationReq"/>
<input type="hidden" name="CriteriaOperationReq" value='<%=ics.GetVar("CriteriaOperationReq")%>' />

<input type="hidden" name="SValueName" value=""/>
<input type="hidden" name="HValueName" value=""/>
<input type="hidden" name="WrongPage" value=""/>
<input type="hidden" name="AssetlistTag" value=""/>		
<input type="hidden" name="STypeName" value=""/>

<string:encode variable="SegmentsRuleScreen" varname="SegmentsRuleScreen"/> 
<input type="hidden" name="ShoppingCart" value='<%=ics.GetVar("SegmentsRuleScreen")%>' />

<string:encode variable="CriteriaOperation" varname="CriteriaOperation"/> 
<input type="hidden" name="CriteriaOperation" value='<%=ics.GetVar("CriteriaOperation")%>' />

<string:encode variable="RebuildScreen" varname="RebuildScreen"/>
<input type="hidden" name="RebuildScreen" value='<%=ics.GetVar("RebuildScreen")%>' />

<string:encode variable="CriteriaRow" varname="CriteriaRow"/>
<input type="hidden" name="CriteriaRow" value='<%=ics.GetVar("CriteriaRow")%>' />

<string:encode variable="CriteriaColumn" varname="CriteriaColumn"/>
<input type="hidden" name="CriteriaColumn" value='<%=ics.GetVar("CriteriaColumn")%>' />

<string:encode variable="SegRuleSetHint" varname="SegRuleSetHint"/>
<input type="hidden" name="SegRuleSetHint" value='<%=ics.GetVar("SegRuleSetHint")%>' />

</cs:ftcs>
